PUT http://localhost:8080/api/devs/19
Authorization: Basic postgres postgres
Accept: application/json
Content-Type: application/json

{
  "number": "0001",
  "statusCode": "31",
  "activeProperties": [
    "STATUS"
  ]
}

###
POST http://localhost:8080/api/devices/
Authorization: Basic postgres postgres
Accept: application/json
Content-Type: application/json

{
  "number": "2000"
}


###
GET http://localhost:8080/api/devs/?size=10&sort=id&id=975&typeGroupId=12
Authorization: Basic postgres postgres
Accept: application/json

###
GET http://localhost:8080/api/devs/1131005975
Authorization: Basic postgres postgres
Accept: application/json

###
DELETE http://localhost:8080/api/devices/97451

###
GET http://localhost:8080/api/devs/send/



###
GET http://localhost:8080/api/rails/
Authorization: Basic postgres postgres
Accept: application/json

###
POST http://localhost:8080/api/rails/
Authorization: Basic postgres postgres
Accept: application/json


###
GET http://localhost:8080/api/dist/
Authorization: Basic postgres postgres
Accept: application/json

###
GET http://localhost:8080/api/rtu/
Authorization: Basic postgres postgres
Accept: application/jsond

###
GET http://localhost:8080/api/obj/
Authorization: Basic postgres postgres
Accept: application/json