---

- name: "Install"
  apt: name=apache2 update_cache=yes state=latest force_apt_get=yes

- name: "Enable mod"
  apache2_module: name={{ item }} state=present
  loop: ['expires', 'headers', 'rewrite', 'ssl']

- name: "Turn on and set them to run on boot"
  service: name=apache2 state=started enabled=yes
  notify: restart apache

- name: "Create document root"
  file:
    path: "/var/www/{{ http_host }}"
    state: directory

- name: "Set up virtualhost"
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
  notify: restart apache

- name: "Enable new site"
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: restart apache

- name: "Disable default site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: restart apache

- name: "Copy test index.html"
  template:
    src: "files/index.html"
    dest: "/var/www/{{ http_host }}/index.html"
  notify: restart apache