# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.box_download_insecure=true
  config.vm.hostname = "dms.uz.zpv"
  config.vm.define "dms_uz"
  config.vm.network  "forwarded_port", guest: 5432, host: 5432, auto_correct: false
  config.vm.network  "private_network", ip: "192.168.50.50", hostname: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.customize ["modifyvm", :id, "--name", "dms_uz"]
    vb.customize ["modifyvm", :id, "--vram", "18"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.provision :ansible_local do |v|
      v.playbook = "./ansible/all_roles.yml"
      v.inventory_path = './ansible/inventory'
      v.limit = 'all'
  end

  config.vm.provision "shell", path: "root-login-enable.sh"

end